DATASET:
  PATH: /data/PETScanner/dataset_new.pkl
MODEL_SAVE_FILENAME: model.pkl
NAME: Validation 1
OUTPUT_DIR: /data/PETScanner/results_new
TRAIN:
  BASE_LEARNING_RATE: 0.0002
  EPOCHS: 150
  LEARNING_DECAY_RATE: 0.2
  LEARNING_DECAY_STEPS: 50
